'use server';

import { revalidatePath } from 'next/cache';
import { requireAdmin } from '@/lib/auth';
import { getSupabaseServer } from '@/lib/supabase/server';

export type BadgeActionResult =
  | { ok: true; count: number }
  | { ok: false; error: string };

/**
 * Bulk-delete the QR badge PNGs for the given employees and soft-delete
 * their `badges` rows (status='deleted'). Employee records and photos are
 * NOT touched. Each badge can be regenerated by re-saving the employee
 * (the upsert in generateAndStoreBadge flips the row back to 'active').
 */
export async function deleteBadges(ids: string[]): Promise<BadgeActionResult> {
  await requireAdmin();
  if (!Array.isArray(ids) || ids.length === 0) {
    return { ok: false, error: 'No employees selected.' };
  }
  const supabase = await getSupabaseServer();

  // Storage paths follow the convention {employee_id}/badge.png
  const paths = ids.map((id) => `${id}/badge.png`);
  await supabase.storage.from('employee-photos').remove(paths);

  // Soft-delete in the badges table.
  await supabase
    .from('badges')
    .update({ status: 'deleted', updated_at: new Date().toISOString() })
    .in('employee_id', ids);

  // Clear the column on employees so the UI reflects the missing badge.
  const { error } = await supabase
    .from('employees')
    .update({ qr_badge_url: null, updated_at: new Date().toISOString() })
    .in('id', ids);
  if (error) return { ok: false, error: error.message };

  revalidatePath('/badges');
  revalidatePath('/employees');
  return { ok: true, count: ids.length };
}
