import { signPaths } from '@/lib/storage';
import { getSupabaseServer } from '@/lib/supabase/server';
import type { BadgeStatus } from '@/lib/types';
import { BadgeExportForm } from './badge-export-form';

export default async function BadgesPage() {
  const supabase = await getSupabaseServer();
  const [{ data: empData }, { data: badgesData }] = await Promise.all([
    supabase
      .from('employees')
      .select('id, employee_code, full_name, active, qr_badge_url')
      .order('active', { ascending: false })
      .order('employee_code'),
    supabase.from('badges').select('employee_id, status'),
  ]);

  const employees = empData ?? [];

  // Per-employee badge status from the badges table. Missing entry =
  // "not generated yet" (employee saved before auto-QR existed, or never saved).
  const statusByEmployeeId: Record<string, BadgeStatus> = {};
  for (const b of (badgesData ?? []) as { employee_id: string; status: BadgeStatus }[]) {
    statusByEmployeeId[b.employee_id] = b.status;
  }

  const qrUrlByPath = await signPaths(
    supabase,
    'employee-photos',
    employees.map((e) => e.qr_badge_url).filter((p): p is string => Boolean(p))
  );

  const qrUrlByEmployeeId: Record<string, string | null> = {};
  for (const e of employees) {
    qrUrlByEmployeeId[e.id] = e.qr_badge_url ? qrUrlByPath[e.qr_badge_url] ?? null : null;
  }

  return (
    <div>
      <div className="mb-5">
        <h1 className="text-3xl font-extrabold tracking-tight">Badges</h1>
        <p className="text-sm mt-1 text-muted">
          Pick employees and export a ZIP containing one QR PNG per badge plus a CSV of
          employee data — ready to hand to your PVC card printing vendor. Soft-deleted
          badges can be regenerated by re-saving the employee.
        </p>
      </div>
      <div className="card p-5">
        <BadgeExportForm
          employees={employees}
          qrUrlByEmployeeId={qrUrlByEmployeeId}
          statusByEmployeeId={statusByEmployeeId}
        />
      </div>
    </div>
  );
}
